name: Sanitizers

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_sanitizers:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Sanitizer for sc-dictionary fs-storage - address",
            os: ubuntu-latest,
            file_memory: "Dictionary",
            sanitizer: "address",
            cc: clang,
            cxx: clang++,
          }
          - {
            name: "Sanitizer for sc-rocksdb fs-storage - address",
            os: ubuntu-latest,
            file_memory: "Rocksdb",
            sanitizer: "address",
            cc: clang,
            cxx: clang++,
          }

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Install dependencies
        id: install_deps
        run: scripts/install_deps_ubuntu.sh --dev --rocksdb

      - name: Restore build caches
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.config.os}}-${{ matrix.config.cxx }}-${{ matrix.config.build_type }}-${{ matrix.config.file_memory }}

      - name: Build
        id: run_cmake
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
          FILE_MEMORY: ${{ matrix.config.file_memory }}
          BUILD_TYPE: ${{ matrix.config.build_type }}
          COVERAGE: OFF
          SANITIZER_TYPE: ${{ matrix.config.sanitizer }}
        run: scripts/ci/make-tests.sh

      - name: Run tests
        id: run_tests
        run: scripts/ci/run-tests.sh
