# This is a basic workflow to help you get started with Actions

name: pull-request-CI

on:
  pull_request:
    branches: [ main, release/** ]

jobs:
  check_pr_commits:
    name: Check commit messages
    runs-on: ubuntu-20.04

    steps:
      - name: GS Commit Message Checker
        # You may pin to the exact commit or the version.
        # uses: GsActions/commit-message-checker@9d8708beab99f811c5fe3a4f98acc4b2f2ba8496
        uses: GsActions/commit-message-checker@v1
        with:
          # A regex pattern to check if a commit message is valid.
          pattern: "((feat|fix|docs|style|refactor|test|build|ci|perf)+(\\([a-z]+(.)+\\))?\\: [a-z]+(.)+)|(Merge(.)*)|(Review fixes(.)*)$"
          # Expression flags change how the expression is interpreted.
          flags: # optional, default is gm
          # A error message which will be returned in case of an error.
          error: "One of commit messages has an incorrect title. Please read the documentation: docs/dev/pr.md"
          # Setting this input to true will exclude the Pull Request title from the check.
          excludeTitle: true # optional, default is false
          # Setting this input to true will exclude the Pull Request description from the check.
          excludeDescription: true # optional, default is false
          # Setting this input to true will check all Pull Request commits
          checkAllCommitMessages: true # optional, default is false
          # you must provide GITHUB_TOKEN to this input if checkAllCommitMessages is true
          accessToken: ${{ secrets.GITHUB_TOKEN }} # optional, default is false
